version: '3'

services:
  php:
    image: php:7.4-fpm
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - .php.env
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www:ro
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  composer:
    image: composer
    container_name: composer
    volumes:
      - ./:/app/
    command: update && install
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./:/var/www:ro
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  ff-proxy:
    image: "harness/ff-proxy:0.9.3"
    container_name: ff-proxy
    volumes:
      - ./config:/config
    environment:
      - DEBUG=${DEBUG}
      - OFFLINE=${OFFLINE}
      - BYPASS_AUTH=${BYPASS_AUTH}
      - AUTH_SECRET=${AUTH_SECRET}
      - ACCOUNT_IDENTIFIER=${ACCOUNT_IDENTIFIER}
      - ORG_IDENTIFIER=${ORG_IDENTIFIER}
      - ADMIN_SERVICE=${ADMIN_SERVICE}
      - ADMIN_SERVICE_TOKEN=${ADMIN_SERVICE_TOKEN}
      - CLIENT_SERVICE=${CLIENT_SERVICE_TOKEN}
      - SDK_BASE_URL=${SDK_BASE_URL}
      - SDK_EVENTS_URL=${SDK_EVENTS_URL}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - API_KEYS=${API_KEYS}
      - TARGET_POLL_DURATION=${TARGET_POLL_DURATION}
    ports:
      - "7001:7000"
    networks:
      - app-network
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge